const SB_URL='https://fqghgisywxnciuorpqim.supabase.co',SB_KEY='sb_publishable_LCeo6dxLwUUiAAVvgZ94zw_rcBCZnP1';
const db=supabase.createClient(SB_URL,SB_KEY,{auth:{persistSession:false,autoRefreshToken:false}}),$=id=>document.getElementById(id),views=['auth','chats','chat'];
let token=localStorage.getItem('privado_session')||'',me=null,conv=null,poll=null;
function show(id){views.forEach(v=>$(v).classList.toggle('on',v===id))}
function e(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function ini(s){return (s||'P').split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase()}
async function rpc(fn,args={}){const {data,error}=await db.rpc(fn,args);if(error)throw error;return data}
function msgErr(x){const m=(x?.message||String(x||'Error')).replace(/^.*P0001:\s*/,'');return ({INVALID_LOGIN:'Identificador o clave incorrectos.',OWNER_NOT_CONFIGURED:'La app aún no está configurada.',INVALID_NAME:'Escribe un nombre válido.',INVALID_IDENTIFIER:'El identificador debe tener entre 3 y 32 caracteres y usar letras, números, punto, guion o guion bajo.',INVALID_PIN:'La clave debe tener entre 6 y 12 números.',MAX_USERS_REACHED:'Ya se alcanzó el máximo de usuarios permitidos.',IDENTIFIER_EXISTS:'Ese identificador ya existe.',PHOTO_TOO_LARGE:'La foto es demasiado pesada.',ALREADY_VIEWED:'Esta foto ya fue vista.',FORBIDDEN:'No tienes permiso.',UNAUTHORIZED:'La sesión venció.'})[m]||m}
function loginForm(){$('loginTab').classList.add('on');$('registerTab').classList.remove('on');$('authCard').innerHTML='<b>Entrar</b><div class="mut">Escribe tu identificador. Si configuraste una clave, escríbela también.</div><input id="lId" class="in" autocapitalize="none" placeholder="Identificador"><input id="lPin" type="password" inputmode="numeric" class="in" placeholder="Clave (opcional)"><div id="aErr" class="err"></div><button id="loginBtn" class="btn">Entrar</button>';$('loginBtn').onclick=async()=>{const b=$('loginBtn');b.disabled=true;$('aErr').textContent='';try{const d=await rpc('app_login',{p_identifier:$('lId').value,p_pin:$('lPin').value.trim()||null});if(d.user.role==='owner'){try{await rpc('app_logout',{p_session_token:d.session_token})}catch{}throw Error('Este enlace es para usuarios.')}token=d.session_token;me=d.user;localStorage.setItem('privado_session',token);await enter()}catch(x){$('aErr').textContent=msgErr(x);b.disabled=false}}}
function registerForm(){$('registerTab').classList.add('on');$('loginTab').classList.remove('on');$('authCard').innerHTML='<b>Crear mi usuario</b><div class="mut">Tú eliges tu nombre, identificador y si quieres usar clave.</div><input id="rName" class="in" placeholder="Tu nombre"><input id="rId" class="in" autocapitalize="none" placeholder="Identificador único"><input id="rPin" type="password" inputmode="numeric" class="in" placeholder="Clave opcional (6 a 12 números)"><div class="warn">La clave es opcional. Sin clave, cualquiera que conozca tu identificador podría entrar a tu cuenta.</div><div id="aErr" class="err"></div><button id="registerBtn" class="btn">Crear usuario</button>';$('registerBtn').onclick=async()=>{const b=$('registerBtn');b.disabled=true;$('aErr').textContent='';try{const d=await rpc('app_self_register',{p_identifier:$('rId').value,p_display_name:$('rName').value,p_pin:$('rPin').value.trim()||null});token=d.session_token;me=d.user;localStorage.setItem('privado_session',token);await enter()}catch(x){$('aErr').textContent=msgErr(x);b.disabled=false}}}
$('loginTab').onclick=loginForm;$('registerTab').onclick=registerForm;
async function init(){loginForm();if(token){try{me=await rpc('app_me',{p_session_token:token});if(me.role==='owner'){token='';me=null;localStorage.removeItem('privado_session');show('auth');return}await enter();return}catch{token='';me=null;localStorage.removeItem('privado_session')}}show('auth')}
async function enter(){show('chats');watermark();await loadChats();stopPoll();poll=setInterval(()=>{if($('chats').classList.contains('on'))loadChats(false)},2500)}
function stopPoll(){if(poll)clearInterval(poll);poll=null}
async function loadChats(wait=true){if(wait)$('chatList').innerHTML='<div class="center mut">Cargando...</div>';try{const a=await rpc('app_conversations_list',{p_session_token:token});$('chatList').innerHTML=a.length?a.map(c=>`<div class="row" data-id="${c.id}" data-title="${e(c.title)}"><div class="avatar">${ini(c.title)}</div><div class="grow"><div class="name">${e(c.title)}</div><div class="preview">${c.last_message?(c.last_message.message_type==='photo'?'📷 Foto':e(c.last_message.body||'')):'Sin mensajes'}</div></div></div>`).join(''):'<div class="center"><div><b>No hay conversaciones</b><div class="mut" style="margin-top:6px">Intenta nuevamente en unos segundos.</div></div></div>';document.querySelectorAll('.row[data-id]').forEach(r=>r.onclick=()=>openChat(r.dataset.id,r.dataset.title))}catch(x){if(msgErr(x).includes('sesión'))logout()}}
async function openChat(id,title){conv={id,title};$('cTitle').textContent=title;$('cAv').textContent=ini(title);show('chat');await loadMsgs();stopPoll();poll=setInterval(loadMsgs,2000)}
$('back').onclick=async()=>{stopPoll();conv=null;show('chats');await loadChats();poll=setInterval(()=>loadChats(false),2500)};
async function loadMsgs(){if(!conv)return;try{const a=await rpc('app_messages_list',{p_session_token:token,p_conversation_id:conv.id}),box=$('messages'),near=box.scrollHeight-box.scrollTop-box.clientHeight<140;box.innerHTML=a.map(m=>{let mine=m.sender_id===me.id,body=m.message_type==='text'?e(m.body):(m.photo_available?`<button class="photo" data-p="${m.id}">${m.view_once?'◉ Ver una sola vez':'📷 Abrir foto'}</button>`:'<div class="photo">Foto no disponible</div>');return `<div class="msg ${mine?'me':''}"><div class="bubble">${!mine?`<div class="small">${e(m.sender_name)}</div>`:''}${body}<div class="stamp">${new Date(m.created_at).toLocaleTimeString('es-CO',{hour:'2-digit',minute:'2-digit'})}</div></div></div>`}).join('');document.querySelectorAll('[data-p]').forEach(b=>b.onclick=()=>openPhoto(b.dataset.p));if(near||!box.dataset.x){box.scrollTop=box.scrollHeight;box.dataset.x='1'}}catch(x){console.log(x)}}
async function send(){const t=$('msgIn').value.trim();if(!t||!conv)return;$('msgIn').value='';try{await rpc('app_message_send_text',{p_session_token:token,p_conversation_id:conv.id,p_body:t});loadMsgs()}catch(x){alert(msgErr(x))}}$('send').onclick=send;$('msgIn').onkeydown=x=>{if(x.key==='Enter')send()};
$('photoBtn').onclick=()=>$('file').click();$('file').onchange=async x=>{const f=x.target.files?.[0];if(!f||!conv)return;try{const z=await compress(f),once=confirm('¿Enviar para ver una sola vez?');await rpc('app_message_send_photo',{p_session_token:token,p_conversation_id:conv.id,p_photo_data:z.data,p_photo_mime:'image/jpeg',p_view_once:once});loadMsgs()}catch(q){alert(msgErr(q))}x.target.value=''};
async function compress(f){const url=URL.createObjectURL(f),im=new Image();await new Promise((a,b)=>{im.onload=a;im.onerror=b;im.src=url});const sc=Math.min(1,1280/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.round(im.width*sc);c.height=Math.round(im.height*sc);c.getContext('2d').drawImage(im,0,0,c.width,c.height);URL.revokeObjectURL(url);let q=.76,d=c.toDataURL('image/jpeg',q);while(d.length>1350000&&q>.4){q-=.08;d=c.toDataURL('image/jpeg',q)}if(d.length>1400000)throw Error('PHOTO_TOO_LARGE');return{data:d.split(',')[1]}}
async function openPhoto(id){try{const p=await rpc('app_photo_open',{p_session_token:token,p_message_id:id});$('photoImg').src=`data:${p.photo_mime};base64,${p.photo_data}`;$('photoModal').classList.add('on')}catch(x){alert(msgErr(x));loadMsgs()}}$('closePhoto').onclick=()=>{$('photoModal').classList.remove('on');$('photoImg').src='';loadMsgs()};
async function logout(){try{if(token)await rpc('app_logout',{p_session_token:token})}catch{}token='';me=null;conv=null;stopPoll();localStorage.removeItem('privado_session');show('auth');loginForm()}$('logout').onclick=logout;
function watermark(){const w=$('wm');w.innerHTML='';for(let i=0;i<36;i++){const s=document.createElement('span');s.textContent=(me?.identifier||'PRIVADO')+' · '+new Date().toLocaleDateString('es-CO');w.appendChild(s)}}document.addEventListener('visibilitychange',()=>$('blur').classList.toggle('on',document.visibilityState!=='visible'));document.addEventListener('copy',x=>x.preventDefault());document.body.style.userSelect='none';
if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw-guest.js').catch(()=>{});init();
